source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

target 'MuxLive' do
  use_frameworks!

  # Pods for MuxLive
  pod 'HaishinKit', '~> 1.1.8'
  pod 'Hue', '~> 5.0.0'
  pod 'Loaf'
  pod 'Alamofire', '~> 5.4'
end
